name: Build and Deploy with Buildpacks

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Desired name for the Docker image'
        required: true
      directory:
        description: 'Select the directory to build'
        required: false
        type: choice
        options:
          - go/mod
          - go/no-imports
          - nodejs/angular-npm
          - nodejs/no-package-manager
          - nodejs/npm
          - nodejs/react-yarn
          - nodejs/vue-npm
          - nodejs/yarn

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository if no repo_url provided
      if: ${{ github.event.inputs.repo_url == '' }}
      uses: actions/checkout@v2

    - name: Install Pack CLI
      run: |
        sudo add-apt-repository ppa:cncf-buildpacks/pack-cli -y
        sudo apt-get update
        sudo apt-get install pack-cli -y

    - name: Grype installation
      run: |
            curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin       

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image using Buildpacks
      run: |
        echo "dir=repo" >> $GITHUB_ENV
        image_name_with_tag="${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.image_name }}:latest"
        cd ${{ github.event.inputs.directory }}
        pack build $image_name_with_tag --builder initializbuildpacks/securepacks
        docker push $image_name_with_tag

    - name: Display Docker Image URI
      run: |
        echo "::notice title=Docker Image URI::${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.image_name }}:latest"

    - name: Run grype
      run: |
          grype ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.image_name }}:latest