on:
  workflow_dispatch:
    inputs:
      path:
         description: 'Source code path'
         required: true
         type: string
    inputs:
      name:
         description: 'Name of image'
         required: true
         type: string
permissions:
      id-token: write
      contents: read
jobs:
  image-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Set up Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.5.3
        with:
          version: 0.33.2

      - name: Pull the builder
        run: |
          docker pull initializbuildpacks/initializ-builder:latest

      - name: Setup the default builder
        run: |
          pack config default-builder initializbuildpacks/initializ-builder:latest

      - name: Build the image 
        run: |
          pack build ${{ inputs.name }}:latest --path ${{ inputs.path }}

      - name: Run the image
        run: |
          docker run --interactive --tty --env PORT=8080 --publish 8080:8080 ${{ inputs.name }}:latest

      - name: Test the image
        run: |
          curl http://localhost:8080

      - name: Stop and remove the container
        run: |
          docker stop $(docker ps -q --filter ancestor=${{ inputs.name }}:latest)
          docker rm $(docker ps -aq --filter ancestor=${{ inputs.name }}:latest)

 
